name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest-small
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
